export const FETCH_FEEDBACK = 'FETCHFEEDBACK'
export const CLEAR_FEEDBACK = 'CLEAR_FEEDBACK'

export const MARK_CHECKED = 'MARK_CHECKED'
export const MARK_CELL = 'MARK_CELL'
export const CLEAR_BOARD = 'CLEAR_BOARD'
export const UPDATE_WINNER = 'UPDATE_WINNER'


export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS'
export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS'
